/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ColaboradorController;
import Model.ColaboradorModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroVoluntario
     */
    ColaboradorController controller = new ColaboradorController();

    public TelaLogin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelCadastro = new javax.swing.JPanel();
        labelEmail = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        barraSenha = new javax.swing.JPasswordField();
        barraEmail = new javax.swing.JTextField();
        botaoAcesso = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setBackground(new java.awt.Color(0, 51, 0));

        painelCadastro.setBackground(new java.awt.Color(204, 255, 255));
        painelCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 102, 0));
        labelEmail.setText("Digite seu e-mail");
        painelCadastro.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 40, -1, -1));

        labelSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(0, 102, 0));
        labelSenha.setText("Digite sua senha");
        painelCadastro.add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\hide.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        painelCadastro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 30));

        barraSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraSenhaActionPerformed(evt);
            }
        });
        painelCadastro.add(barraSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 195, 39));

        barraEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraEmailActionPerformed(evt);
            }
        });
        painelCadastro.add(barraEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 71, 249, 39));

        botaoAcesso.setBackground(new java.awt.Color(0, 102, 0));
        botaoAcesso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoAcesso.setText("Acessar");
        botaoAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcessoActionPerformed(evt);
            }
        });
        painelCadastro.add(botaoAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 238, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Cadastre-se");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        painelCadastro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 279, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Esqueci minha senha");
        painelCadastro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 279, -1, -1));

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(505, 505, 505)
                .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(524, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraSenhaActionPerformed

    private void barraEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraEmailActionPerformed

    private void botaoAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcessoActionPerformed

        String email = barraEmail.getText();
        String senha = new String(barraSenha.getPassword());

        if (email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o e-mail e a senha.");
        } else {
            ColaboradorModel usuarioLogado = controller.login(email, senha);

            if (usuarioLogado != null) {
                JOptionPane.showMessageDialog(null, "Login realizado com sucesso!\nBem-vindo(a), " + usuarioLogado.getNome());
                // Aqui você pode abrir a próxima tela ou salvar os dados do usuário logado
               TelaHome home= new TelaHome(usuarioLogado);
               home.setVisible(true);
               dispose();
            } else {
                JOptionPane.showMessageDialog(null, "E-mail ou senha inválidos.");
            }
        }

        
    }//GEN-LAST:event_botaoAcessoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        TelaCadastroColaboradores tela = new TelaCadastroColaboradores();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked
    boolean senhaVisivel=false;
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if(senhaVisivel==false){
        barraSenha.setEchoChar((char) 0);
        senhaVisivel=true;
        }else{
            barraSenha.setEchoChar('*');
            senhaVisivel=false;
        }
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraEmail;
    private javax.swing.JPasswordField barraSenha;
    private javax.swing.JToggleButton botaoAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
