/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ColaboradorController;

import Model.ColaboradorModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class TelaCadastroColaboradores extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroColaboradores
     */
    ColaboradorController controller = new ColaboradorController();

    public TelaCadastroColaboradores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomedigitar = new javax.swing.JTextField();
        cpfdigitar = new javax.swing.JFormattedTextField();
        dataNascimento = new javax.swing.JFormattedTextField();
        escolherfuncao = new javax.swing.JComboBox<>();
        nomecompleto = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        datadenascimento = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        funcao = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        cadastro = new javax.swing.JLabel();
        emaildigitar = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        sexoEscolher = new javax.swing.JComboBox<>();
        senhadigitar = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(nomedigitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 104, 360, -1));

        try {
            cpfdigitar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfdigitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfdigitarActionPerformed(evt);
            }
        });
        jPanel1.add(cpfdigitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 144, 100, -1));

        try {
            dataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(dataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 184, 80, -1));

        escolherfuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretário", "Lider", "Vice-lider", "Tesoureiro" }));
        jPanel1.add(escolherfuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 234, -1, -1));

        nomecompleto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nomecompleto.setForeground(new java.awt.Color(0, 51, 0));
        nomecompleto.setText("Nome Completo:");
        jPanel1.add(nomecompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 107, -1, -1));

        cpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cpf.setForeground(new java.awt.Color(0, 51, 0));
        cpf.setText("CPF:");
        jPanel1.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 147, -1, -1));

        datadenascimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        datadenascimento.setForeground(new java.awt.Color(0, 51, 0));
        datadenascimento.setText("Data de nascimento:");
        jPanel1.add(datadenascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 187, -1, -1));

        sexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sexo.setForeground(new java.awt.Color(0, 51, 0));
        sexo.setText("Sexo:");
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 187, -1, -1));

        funcao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        funcao.setForeground(new java.awt.Color(0, 51, 0));
        funcao.setText("Função:");
        jPanel1.add(funcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 237, -1, -1));

        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(0, 51, 0));
        email.setText("E-mail:");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        senha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        senha.setForeground(new java.awt.Color(0, 51, 0));
        senha.setText("Criar senha:");
        jPanel1.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        cadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cadastro.setForeground(new java.awt.Color(0, 153, 51));
        cadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastro.setText("Cadastro");
        jPanel1.add(cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 190, 52));

        emaildigitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaildigitarActionPerformed(evt);
            }
        });
        jPanel1.add(emaildigitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 340, -1));

        cadastrar.setBackground(new java.awt.Color(0, 204, 0));
        cadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        sexoEscolher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jPanel1.add(sexoEscolher, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));
        jPanel1.add(senhadigitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cpfdigitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfdigitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfdigitarActionPerformed

    private void emaildigitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaildigitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emaildigitarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
        String nome = nomedigitar.getText();
        String email = emaildigitar.getText();
        String sexo = (String) sexoEscolher.getSelectedItem();
        String senha = new String(senhadigitar.getPassword());
        String cpf = cpfdigitar.getText();
        String funcao = (String) escolherfuncao.getSelectedItem();
        String dataNasc = dataNascimento.getText();

// Verificar se algum campo está vazio
        if (nome.isEmpty() || email.isEmpty() || sexo == null || sexo.isEmpty()
                || senha.isEmpty() || cpf.isEmpty() || funcao == null || funcao.isEmpty()
                || dataNasc.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos antes de cadastrar.");
        } else {
            ColaboradorModel funcionario = new ColaboradorModel();
            funcionario.setNome(nome);
            funcionario.setEmail(email);
            funcionario.setSexo(sexo);
            funcionario.setSenha(senha);
            funcionario.setCpf(cpf);
            funcionario.setFuncao(funcao);
            funcionario.setDataNascimento(dataNasc);

            Boolean result = controller.cadastrar(funcionario);
            if (result != null) {
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                
                TelaLogin tl = new TelaLogin();
                tl.setVisible(true);
                dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao Cadastrar!");
            }
        }


    }//GEN-LAST:event_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroColaboradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel cadastro;
    private javax.swing.JLabel cpf;
    private javax.swing.JFormattedTextField cpfdigitar;
    private javax.swing.JFormattedTextField dataNascimento;
    private javax.swing.JLabel datadenascimento;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emaildigitar;
    private javax.swing.JComboBox<String> escolherfuncao;
    private javax.swing.JLabel funcao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomecompleto;
    private javax.swing.JTextField nomedigitar;
    private javax.swing.JLabel senha;
    private javax.swing.JPasswordField senhadigitar;
    private javax.swing.JLabel sexo;
    private javax.swing.JComboBox<String> sexoEscolher;
    // End of variables declaration//GEN-END:variables
}
